name: Pull Request Creation

on:
  # Add the `workflow_dispatch` event if you want to be able to manually run this workflow from the UI. For more information, see [`workflow_dispatch`](/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch).
  workflow_dispatch:
  # Add the `push` event, so that the workflow runs automatically every time a commit is pushed to a branch called `main`. For more information, see [`push`](/actions/using-workflows/events-that-trigger-workflows#push).
  push:
    branches:
      - main

jobs:
  pullRequestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_pull_requests
        with:
          query: |
            query user($login: String!) {
              user(login: $login) {
                pullRequests(last: 100, orderBy: {field: CREATED_AT, direction: DESC}) {
                  totalCount
                  nodes {
                    title
                    url
                    state
                    mergedBy {
                      avatarUrl
                      url
                      login
                    }
                    createdAt
                    number
                    changedFiles
                    additions
                    deletions
                    baseRepository {
                      name
                      url
                      owner {
                        avatarUrl
                        login
                        url
                      }
                    }
                  }
                  pageInfo {
                    hasNextPage
                    endCursor
                  }
                }
              }
            }
          variables: '{"login":"lrudolph333"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'Pull Requests Data: ${{ steps.get_pull_requests.outputs.data }}'"
